# 一.ndarray
## 1.ndarray的特性
### 多维性


In [ ]:
import numpy as np
from tornado.util import unicode_type

arr = np.array(5)
print(arr)
print("维度：", arr.ndim)
arr = np.array([1, 2, 3])
print(arr)
print("维度：", arr.ndim)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("维度：", arr.ndim)


### 同质性

In [6]:
arr = np.array([1,1.3])
print(arr)


[1.  1.3]


## 2.ndarray的属性

In [14]:
arr=np.array(1)
print(arr)
print("数组的形状：",arr.shape)
print("数组的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的类型：",arr.dtype)
print("元素的转置：",arr.T)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
元素的类型： int64
元素的转置： 1


In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("数组的形状：",arr.shape)
print("数组的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的类型：",arr.dtype)
print("元素的转置：",arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
元素的类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


In [18]:
arr=np.array([1,2,3])
print(arr)
print("数组的形状：",arr.shape)
print("数组的维度：",arr.ndim)
print("元素的个数：",arr.size)
print("元素的类型：",arr.dtype)
print("元素的转置：",arr.T)

[1 2 3]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
元素的类型： int64
元素的转置： [1 2 3]


### 3.ndarrary的创建

In [19]:
# 基础的创建方法
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [20]:
list1=[1,2,3]
arr=np.array(list1,dtype=np.float64)
print(arr)
print(arr.ndim)

[1. 2. 3.]
1


In [21]:
#copy
arr1=np.copy(arr)
print(arr1)


[1. 2. 3.]


In [25]:
#预定义形状的
# 全零 全一  未初始化  固定值
# 全零
arr=np.zeros((3,4),dtype=int)
print(arr)
print(arr.ndim)
print(arr.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
2
int64


In [26]:
#全一
arr=np.ones((3,4),dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [28]:
# 未初始化的
arr=np.empty((3,4),dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [32]:
arr=np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [33]:
arr1=np.ones_like(arr)
print(arr1)
arr1=np.zeros_like(arr)
print(arr1)
arr1=np.empty_like(arr)
print(arr1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [34]:
#等差数列 1 2 3 4 5
arr=np.arange(1,5,1)
print(arr)

[1 2 3 4]


### (start , end , step)  dont include end

In [39]:
# 等间隔数列
arr=np.linspace(0,100,5,dtype=int)   #start to end  中取 5个数
print(arr)

[  0  25  50  75 100]


In [38]:
arr=np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]


In [40]:
# 对数间隔数列
arr=np.logspace(0,4,3,base=2)
print(arr)

[ 1.  4. 16.]


In [42]:
# 特殊矩阵
# 单位举证 eye
arr=np.eye(3)
print(arr)
arr1=np.eye(2,3,dtype=int)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]]


In [44]:
# 对角矩阵 diag
arr=np.diag([5,1,2,3])
print(arr)


[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [45]:
# 随机数组的生成
# 生成0到1之间的随机的浮点数（均匀分布）
arr=np.random.rand(2,3)
print(arr)

[[0.92717193 0.87227623 0.37327892]
 [0.62406326 0.15696268 0.28654174]]


In [46]:
# 生成指定范围区间的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[3.05719484 4.62402176 5.5783861 ]
 [5.92863757 3.54508667 3.07855071]]


In [48]:
# 生成指定范围区间的随机zheng数
arr=np.random.randint(3,60,(2,3))
print(arr)

[[15  6 56]
 [ 8 18 54]]


In [49]:
# 生成随机数列（正态分布）
arr=np.random.randn(2,3)
print(arr)


[[ 0.67952784 -0.44118312 -0.36326673]
 [-0.76446888 -0.27520863  0.72197198]]


In [50]:
# 设置随机种子
np.random.seed(20)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


### 4.ndarray 的数据类型
布尔类型 bool

整数类型 int  unit

浮点数 float

复数 complex

In [52]:
arr=np.array([1,0,3,0],dtype=bool)
print(arr)

[ True False  True False]


In [54]:
arr=np.array([1,0,127,0],dtype=np.int8)
print(arr)

[  1   0 127   0]


5.索引与切片


In [4]:
# 一维数组的索引与切片
import numpy as np
arr = np.random.randint(1,100,20)
print(arr)

[27  3 82 88 13 82 79 29 55 93 12 60  7 62  5 49 29 29 48 89]


In [5]:
print(arr[0])


27


In [6]:
print(arr[3])

88


In [14]:
print(arr[:]) #获取数据
print(arr[3:])
print(arr[3:5]) # 左半包右边不包 start : end+1
print(arr[slice(3,5)])
print(arr[slice(3,12,5)])
print(arr[arr>10])
print(arr[(arr>10) & (arr<50)])  # and 必须用& &&&&&&&

[27  3 82 88 13 82 79 29 55 93 12 60  7 62  5 49 29 29 48 89]
[88 13 82 79 29 55 93 12 60  7 62  5 49 29 29 48 89]
[88 13]
[88 13]
[88 55]
[27 82 88 13 82 79 29 55 93 12 60 62 49 29 29 48 89]
[27 13 29 12 49 29 29 48]


In [15]:
# 二维数组的索引与切片
arr=np.random.randint(1,100,(4,8))
print(arr)

[[57 15 87 51 20 58 17 41]
 [59 30 14 19 23 61 75 52]
 [44 92 91  4 43 82 81 45]
 [36 67 93 67 30 56 97 69]]


In [21]:
print(arr[1,3])
print(arr[:])
print(arr[1,:])
print(arr[arr>50]) #输出为一维数组
print(arr[2][arr[2]>50])

19
[[57 15 87 51 20 58 17 41]
 [59 30 14 19 23 61 75 52]
 [44 92 91  4 43 82 81 45]
 [36 67 93 67 30 56 97 69]]
[59 30 14 19 23 61 75 52]
[57 87 51 58 59 61 75 52 92 91 82 81 67 93 67 56 97 69]
[92 91 82 81]


5.ndarray的运算

In [23]:
# 算数运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [25]:
c=[1,2,3]
d=[4,5,6]
print(c+d)
for i in range(len(c)):
    d[i]=c[i]+d[i]
print(d)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [26]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [0.7        0.72727273 0.75      ]]


In [29]:
# 广播机制：1.获取形状 2。判断是否可以
# 同一维度：相同、1
a=np.array([1,2,3]) #1*3
b=np.array([[4],[5],[6]])     #1*2
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a @ b)
print(a*b)

[[ 48  54  60]
 [111 126 141]
 [174 198 222]]
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]


# 2.3 numpy 中的常用函数
## 1.基本数学函数


In [34]:
# 计算平方根
print(np.sqrt(9)) # sqrt 返回浮点数
print(np.sqrt([1,4,9]))
arr=np.array([1,25,9])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 3.]


In [37]:
# 计算指数  e^x
print(np.exp(1))

2.718281828459045


In [39]:
#计算自然对数 Ln y= x
print(np.log(2.71))

0.9969486348916096


In [41]:
#计算正弦、余弦
print(np.sin(np.pi/2))

1.0


In [42]:
#计算绝对值
arr=np.array([1,25,-9])
print(abs(arr))

[ 1 25  9]


In [43]:
# 计算a 的 b 次幂
print(np.power(arr,2))

[  1 625  81]


In [44]:
# 四舍五入
print(np.round([3.2,4.5,6.7]))

[3. 4. 7.]


In [45]:
# 向上取整，向下取整
arr=np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [46]:
# 检测缺失值NaN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

2.统计函数

求和、计算平均值、中位数、标准差、方差

最大值、最小值

分位数、累计和、累计差

In [49]:
arr=np.random.randint(1,20,8)
print(arr)

[ 2  4 16 13 15 15  4 16]


In [51]:
# 求和
print(np.sum([1,3,2]))
print(np.sum(arr))

6
85


In [53]:
# 平均值
print(np.mean(arr))
print(np.mean([1,3,2]))

10.625
2.0


In [54]:
#计算中位数 奇数取中间数，偶数个中间两个数除二
print(np.median(arr))

14.0


In [56]:
# 计算标准差、方差
print(np.var([1,3,2]))   #方差  2 和1 2 3 都比较接近
print(np.std([1,3,2]))

0.6666666666666666
0.816496580927726


In [59]:
# 计算最大值 最小值   索引
print(arr)
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

[ 2  4 16 13 15 15  4 16]
16 2
2 0


In [61]:
# 分位数   percnetile
print(np.median([1,2,3]))
print(np.median([1,2,3,4]))

2.0
2.5


In [64]:
print(np.percentile(arr,50))
print(np.median(arr))
print(np.percentile(arr,100))

14.0
14.0
16.0


In [67]:
# 累积和 累积积
print(arr)
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 2  4 16 13 15 15  4 16]
[ 2  6 22 35 50 65 69 85]
[       2        8      128     1664    24960   374400  1497600 23961600]


## 比较函数

大于、小于、等于

逻辑与、或、非

检查数组中是否有一个True

In [71]:
# 是否大于
print(np.greater([3,4,5,6,7],3))
# 是否小于
print(np.less([3,4,5,6,7],3))
# 是否等于
print(np.equal([3,4,5,6,3],3))
print(np.equal([3,4,5,6,7],[3,4,5,6,7]))

[False  True  True  True  True]
[False False False False False]
[ True False False False  True]
[ True  True  True  True  True]


In [74]:
# 逻辑与或非
print(np.logical_and([1,0],[1,1]))
print(np.logical_not([1,0]))
print(np.logical_or([1,0],[1,1]))

[ True False]
[False  True]
[ True  True]


In [76]:
# 至少有一个元素为true
print(np.any([1,0]))
# 全部元素为true
print(np.all([1,0]))

True
False


In [78]:
# 自定义条件
# print(np.where(条件，符合条件取得值，不符合条件取得值））
arr=np.random.randint(1,20,5)
print(arr)

[12 19 13  7 19]


In [79]:
print(np.where(arr>10,arr,0))

[12 19 13  0 19]


In [81]:
print(np.where(arr<8,"不及格",np.where(arr<14,"良好","优秀 ")))

['良好' '优秀 ' '良好' '不及格' '优秀 ']


In [6]:
# 排序函数
import numpy as np
np.random.seed(0)
arr=np.random.randint(1,20,5)
print(arr)
# arr.sort()
# print(arr)
print(np.sort(arr)) # 不改变原始数组
print(np.argsort(arr))

[13 16  1  4  4]
[ 1  4  4 13 16]
[2 3 4 0 1]


In [7]:
# 去重函数
print(np.unique(arr))

[ 1  4 13 16]


In [9]:
# 数组的拼接
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[ 2  4  6  8 10]
[1 2 3 4 5 1 2 3 4 5]


In [12]:
# 数组的分割
print(np.split(arr1,5)) # 等分
print(np.split(arr1,[2,4])) # 位置切割

[array([1]), array([2]), array([3]), array([4]), array([5])]
[array([1, 2]), array([3, 4]), array([5])]


In [16]:
# 调整数组的形状
print(np.reshape(arr1,(5,1)))

[[1]
 [2]
 [3]
 [4]
 [5]]


### 3.计算函数训练

In [23]:
temps=np.array([28,30,29,31,32,30,29])
print(temps)
print('mean temperature','%.3f'%np.mean(temps))
print('maxtemperature',np.max(temps))
print('mintemperature',np.min(temps))
print('气温超过30度的天数')
print(len(temps[np.where(temps>30)]))

[28 30 29 31 32 30 29]
mean temperature 29.857
maxtemperature 32
mintemperature 28
气温超过30度的天数
2


In [26]:
print(np.where(temps>30,1,0))
print(np.cumsum(np.where(temps>30,1,0))[-1])

[0 0 0 1 1 0 0]
2


In [32]:
score=np.array([85,90,78,88,92])
print('maen score',np.mean(score))
print('median score',np.median(score))
print('std score','%.3f'%np.std(score)) #标准差
print('var score','%.3f'%np.var(score))
print(score/10)

maen score 86.6
median score 88.0
std score 4.883
var score 23.840
[8.5 9.  7.8 8.8 9.2]


In [35]:
"""

题目4：随机数据生成

生成一个（3，4）的随机整数数组，范围[0，10）。

计算每列的最值和每行的最小值。

—将数组中的所有奇数替换为—1。

"""
arr=np.random.randint(0,10,(3,4))
print(arr)
print('每列的最大值',np.max(arr,axis=0))  #axis=0 wei lie  1wei hang
print('meileide min',np.min(arr,axis=0))

[[5 0 2 3]
 [8 1 3 3]
 [3 7 0 1]]
每列的最大值 [8 7 3 3]
meileide min [3 0 0 1]


In [37]:
arr1=np.where(arr%2==1,-1,arr)
print(arr1)

[[-1  0  2 -1]
 [ 8 -1 -1 -1]
 [-1 -1  0 -1]]


In [48]:
"""
题目5：数组变形

创建一个1到12的一维数组，并转换为（3，4）的二维数组。

—计算每行的和与每列的平均值。

—将数组展平为一维数组。

"""
arr=np.arange(1,13)
print(arr)
print(np.reshape(arr,(3,4)))
arr=np.reshape(arr,(3,4))
print('每行的和：',np.sum(arr,axis=1))
print('每列的平均值',np.mean(arr,axis=0))
print(np.reshape(arr,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和： [10 26 42]
每列的平均值 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
